Models/InvoiceModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace InvoiceManagementWebApp.Models
{
    public class InvoiceModel
    {
        public int Id { get; set; }

        [Display(Name = "Supplier")]
        public SupplierModel SelectedSupplier { get; set; }

        [Required]
        [Display(Name = "Supplier")]
        public int SelectedSupplierId { get; set; }

        // Broj racuna(fakture)
        [Display(Name = "Invoice number")]
        [Required]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Invoice number must be between 3 and 20 characters.")]
        [RegularExpression(@"^[A-Za-z0-9\-]+$", ErrorMessage = "Invoice number can only contain letters, numbers, and dashes.")]
        public string InvoiceNum { get; set; }

        // Valuta placanja
        [Display(Name = "Payment dead line")]
        [DataType(DataType.Date)]
        public DateTime PaymentDeadline { get; set; }

        // Datum prijema robe
        [Display(Name = "Delivery Date")]
        [DataType(DataType.Date)]
        public DateTime DeliveryDate { get; set; }

        // Poziv na broj
        [Display(Name = "Refference number")]
        [Required]
        [StringLength(15, MinimumLength = 5, ErrorMessage = "Reference number must be between 5 and 15 characters.")]
        [RegularExpression(@"^[A-Za-z0-9\-]+$", ErrorMessage = "Reference number can only contain letters, numbers, and dashes.")]
        public string ReferenceNumber { get; set; }

        // Iznos 
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Amount { get; set; }

        public bool IsPaid { get; set; }
    }
}

Controllers/InvoiceModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InvoiceManagementWebApp.Data;
using InvoiceManagementWebApp.Models;
using System.Diagnostics;

namespace InvoiceManagementWebApp.Controllers
{
    public class InvoiceModelsController : Controller
    {
        private readonly InvoiceModelContext _context;

        public InvoiceModelsController(InvoiceModelContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Paid(int id)
        {
            var invoice = await _context.InvoiceModel.FindAsync(id);
            if (invoice == null)
            {
                return NotFound();
            }

            // Logic to mark the invoice as paid (e.g., set IsPaid property)
            invoice.IsPaid = true;

            _context.Update(invoice);
            await _context.SaveChangesAsync();

            // Remove the paid invoice from the list
            var invoices = await _context.InvoiceModel
                .Where(i => !i.IsPaid)
                .Include(i => i.SelectedSupplier)
                .ToListAsync();

            return View("Index", invoices);
        }


        public IActionResult PaidInvoices()
        {
            var paidInvoices = _context.InvoiceModel
                                     .Where(i => i.IsPaid)
                                     .Include(i => i.SelectedSupplier) // Include the navigation property
                                     .ToList();

            return View(paidInvoices);
        }

        public async Task<IActionResult> Index(string searchString, DateTime paymentDeadline)
        {
            if (_context.InvoiceModel == null)
            {
                return Problem("Entity set 'InvoiceModelContext.InvoiceModel' is null.");
            }

            var invoices = from i in _context.InvoiceModel
                           select i;

            if (!String.IsNullOrEmpty(searchString))
            {
                invoices = invoices.Where(i => i.SelectedSupplier.SupplierName.Contains(searchString));
            }

            if (paymentDeadline != default(DateTime))
            {
                invoices = invoices.Where(i => i.PaymentDeadline.Date == paymentDeadline.Date);
            }

            invoices = invoices.OrderBy(i => i.PaymentDeadline);

            return View(await invoices.Include(i => i.SelectedSupplier).ToListAsync());
        }


        // GET: InvoiceModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoiceModel = await _context.InvoiceModel
                .Include(i => i.SelectedSupplier)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (invoiceModel == null)
            {
                return NotFound();
            }

            return View(invoiceModel);
        }



        // GET: InvoiceModels/Create
        public IActionResult Create()
        {
            ViewBag.Suppliers = new SelectList(_context.SupplierModel, "Id", "SupplierName");
            return View();
        }


        // POST: InvoiceModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SelectedSupplierId,InvoiceNum,PaymentDeadline,DeliveryDate,ReferenceNumber,Amount")] InvoiceModel invoiceModel)
        {
            if (ModelState.IsValid)
            {
                // Create a new InvoiceModel instance
                var newInvoice = new InvoiceModel
                {
                    SelectedSupplierId = invoiceModel.SelectedSupplierId,
                    InvoiceNum = invoiceModel.InvoiceNum,
                    PaymentDeadline = invoiceModel.PaymentDeadline,
                    DeliveryDate = invoiceModel.DeliveryDate,
                    ReferenceNumber = invoiceModel.ReferenceNumber,
                    Amount = invoiceModel.Amount
                };

                _context.Add(newInvoice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Repopulate the suppliers dropdown in case of validation error
            ViewBag.Suppliers = new SelectList(_context.SupplierModel, "Id", "SupplierName", invoiceModel.SelectedSupplierId);
            return View(invoiceModel);
        }


        // GET: InvoiceModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoiceModel = await _context.InvoiceModel.FindAsync(id);
            if (invoiceModel == null)
            {
                return NotFound();
            }

            ViewBag.Suppliers = new SelectList(_context.SupplierModel, "Id", "SupplierName", invoiceModel.SelectedSupplierId);
            return View(invoiceModel);
        }

        // POST: InvoiceModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SelectedSupplierId,InvoiceNum,PaymentDeadline,DeliveryDate,ReferenceNumber,Amount")] InvoiceModel invoiceModel)
        {
            if (id != invoiceModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Load the existing invoice from the database
                    var existingInvoice = await _context.InvoiceModel.FindAsync(id);
                    if (existingInvoice == null)
                    {
                        return NotFound();
                    }

                    // Update the properties of the existing invoice with the new values
                    existingInvoice.SelectedSupplierId = invoiceModel.SelectedSupplierId;
                    existingInvoice.InvoiceNum = invoiceModel.InvoiceNum;
                    existingInvoice.PaymentDeadline = invoiceModel.PaymentDeadline;
                    existingInvoice.DeliveryDate = invoiceModel.DeliveryDate;
                    existingInvoice.ReferenceNumber = invoiceModel.ReferenceNumber;
                    existingInvoice.Amount = invoiceModel.Amount;

                    _context.Update(existingInvoice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceModelExists(invoiceModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Suppliers = new SelectList(_context.SupplierModel, "Id", "SupplierName", invoiceModel.SelectedSupplierId);
            return View(invoiceModel);
        }


        // GET: InvoiceModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoiceModel = await _context.InvoiceModel
                .Include(i => i.SelectedSupplier) // Include the navigation property
                .FirstOrDefaultAsync(m => m.Id == id);

            if (invoiceModel == null)
            {
                return NotFound();
            }

            return View(invoiceModel);
        }


        // POST: InvoiceModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invoiceModel = await _context.InvoiceModel.FindAsync(id);
            _context.InvoiceModel.Remove(invoiceModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InvoiceModelExists(int id)
        {
            return _context.InvoiceModel.Any(e => e.Id == id);
        }
    }
}

Views/InvoiceModels/Create.cshtml
@model InvoiceManagementWebApp.Models.InvoiceModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create new Invoice</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SelectedSupplierId" class="control-label">Supplier</label>
                @Html.DropDownListFor(model => model.SelectedSupplierId, (SelectList)ViewBag.Suppliers, "Select a supplier...", new { @class = "form-control", id = "SelectedSupplierId" })
                <span asp-validation-for="SelectedSupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvoiceNum" class="control-label"></label>
                <input asp-for="InvoiceNum" class="form-control" />
                <span asp-validation-for="InvoiceNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDeadline" class="control-label"></label>
                <input asp-for="PaymentDeadline" class="form-control" />
                <span asp-validation-for="PaymentDeadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label"></label>
                <input asp-for="DeliveryDate" class="form-control" />
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReferenceNumber" class="control-label"></label>
                <input asp-for="ReferenceNumber" class="form-control" />
                <span asp-validation-for="ReferenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/InvoiceModels/Delete.cshtml
@model InvoiceManagementWebApp.Models.InvoiceModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SelectedSupplier.SupplierName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SelectedSupplier.SupplierName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceNum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InvoiceNum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentDeadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentDeadline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReferenceNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/InvoiceModels/Details.cshtml
@model InvoiceManagementWebApp.Models.InvoiceModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SelectedSupplier.SupplierName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SelectedSupplier.SupplierName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceNum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InvoiceNum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentDeadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentDeadline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReferenceNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/InvoiceModels/Edit.cshtml
@model InvoiceManagementWebApp.Models.InvoiceModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SelectedSupplierId" class="control-label">Supplier</label>
                <select asp-for="SelectedSupplierId" class="form-control" asp-items="ViewBag.Suppliers">
                    <option value="">Select a supplier...</option>
                </select>
                <span asp-validation-for="SelectedSupplierId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="InvoiceNum" class="control-label"></label>
                <input asp-for="InvoiceNum" class="form-control" />
                <span asp-validation-for="InvoiceNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDeadline" class="control-label"></label>
                <input asp-for="PaymentDeadline" class="form-control" />
                <span asp-validation-for="PaymentDeadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label"></label>
                <input asp-for="DeliveryDate" class="form-control" />
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReferenceNumber" class="control-label"></label>
                <input asp-for="ReferenceNumber" class="form-control" />
                <span asp-validation-for="ReferenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/InvoiceModels/Index.cshtml
@model IEnumerable<InvoiceManagementWebApp.Models.InvoiceModel>

@{
    ViewData["Title"] = "All Invoices";
}

<h1>List of all Invoices</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="InvoiceModels" asp-action="Index" method="get">
    <p>
        Supplier name: <input type="text" name="searchString" />
        Payment Deadline: <input type="date" name="paymentDeadline" />
        <input type="submit" value="Filter" />
        <a asp-controller="InvoiceModels" asp-action="Index" class="btn btn-secondary">Clear Filters</a>
    </p>
</form>
<a asp-controller="InvoiceModels" asp-action="PaidInvoices" class="bigger-link">Paid Invoices</a>


<table class="table">
    <thead>
        <tr class="text-center">
            <th>
                @Html.DisplayNameFor(model => model.SelectedSupplier.SupplierName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvoiceNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentDeadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReferenceNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (!item.IsPaid)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.SelectedSupplier.SupplierName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InvoiceNum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PaymentDeadline)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeliveryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReferenceNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                        <a asp-action="Paid" asp-route-id="@item.Id">Paid</a>
                    </td>
                </tr>
                }
            }
    </tbody>
</table>

Views/InvoiceModels/PaidInvoices.cshtml
@model IEnumerable<InvoiceManagementWebApp.Models.InvoiceModel>

@{ ViewData["Title"] = "Paid Invoices"; }

<h1>Paid Invoices</h1>

<table class="table">
    <thead>
        <tr class="text-center">
            <th>
                @Html.DisplayNameFor(model => model.SelectedSupplier.SupplierName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvoiceNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentDeadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReferenceNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(i => i.IsPaid))
        {
<tr class="text-center">
    <td>
        @Html.DisplayFor(modelItem => item.SelectedSupplier.SupplierName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.InvoiceNum)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PaymentDeadline)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DeliveryDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ReferenceNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Amount)
    </td>
</tr>}
    </tbody>
</table>